spring:
  thymeleaf:
    cache: false
    mode: HTML5
    check-template: true
    servlet.content-type: text/html
    encoding: UTF-8
    perfix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**    #静态资源的请求方式
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  datasource:
    url: jdbc:mysql://localhost:3306/weblog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/weblog/dao/mappers/*.xml
  type-aliases-package: com.weblog.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count:countSql
