spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**    #静态资源的请求方式
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  datasource:
    name: sv
    url: jdbc:mysql://localhost:3306/weblog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com.weblog.mappers/*.xml
  type-aliases-package: com.weblog.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
